name: Node.js CI

on:
  #push:
    #branches: [ "main" ]  # Workflow chạy khi có push vào nhánh 'main'
  pull_request:
    branches: [ "main" ]  # Workflow chạy khi có pull request vào nhánh 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    strategy:
      matrix:
        node-version: [18.x, 20.x]  # Kiểm tra trên nhiều phiên bản Node.js
        # Bạn có thể tìm lịch phát hành Node.js tại https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4  # Checkout mã nguồn từ repository

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4  # Cài đặt Node.js và cấu hình cache npm
      with:
        node-version: ${{ matrix.node-version }}  # Sử dụng phiên bản Node.js từ matrix
        cache: 'npm'  # Sử dụng caching cho npm (cải thiện hiệu suất)

    - run: npm ci  # Cài đặt phụ thuộc với npm ci (dành cho CI)
    - run: npm run build --if-present  # Nếu có script 'build', chạy nó
    - run: npm test  # Chạy các bài kiểm tra (npm test)
